### ISSUE TITLE
Crash on double sign up??

### ISSUE THREAD

**Issue by gabrc52** [sipb/interstellar#3]
The NodeJS server crashed and this is in the logs

```
Jul 10 14:01:01 interstellar node[798]: REDACTED registered
Jul 10 14:01:02 interstellar node[798]: REDACTED registered
Jul 10 14:01:02 interstellar node[798]: E11000 duplicate key error collection: interstellar.users index: email_1 dup key: { email: "REDACTED@mit.edu" }
Jul 10 14:01:02 interstellar node[798]: node:events:491
Jul 10 14:01:02 interstellar node[798]:       throw er; // Unhandled 'error' event
Jul 10 14:01:02 interstellar node[798]:       ^
Jul 10 14:01:02 interstellar node[798]: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Jul 10 14:01:02 interstellar node[798]:     at new NodeError (node:internal/errors:387:5)
Jul 10 14:01:02 interstellar node[798]:     at ServerResponse.setHeader (node:_http_outgoing:644:11)
Jul 10 14:01:02 interstellar node[798]:     at ServerResponse.header (/home/interstellar/interstellar/node_modules/express/lib/response.js:776:10)
Jul 10 14:01:02 interstellar node[798]:     at ServerResponse.send (/home/interstellar/interstellar/node_modules/express/lib/response.js:170:12)
Jul 10 14:01:02 interstellar node[798]:     at ServerResponse.json (/home/interstellar/interstellar/node_modules/express/lib/response.js:267:15)
Jul 10 14:01:02 interstellar node[798]:     at ServerResponse.send (/home/interstellar/interstellar/node_modules/express/lib/response.js:158:21)
Jul 10 14:01:02 interstellar node[798]:     at /home/interstellar/interstellar/server/auth.js:106:34
Jul 10 14:01:02 interstellar node[798]:     at /home/interstellar/interstellar/node_modules/mongoose/lib/model.js:5074:18
Jul 10 14:01:02 interstellar node[798]:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
Jul 10 14:01:02 interstellar node[798]: Emitted 'error' event on Function instance at:
Jul 10 14:01:02 interstellar node[798]:     at /home/interstellar/interstellar/node_modules/mongoose/lib/model.js:5076:15
Jul 10 14:01:02 interstellar node[798]:     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
Jul 10 14:01:02 interstellar node[798]:   code: 'ERR_HTTP_HEADERS_SENT'

```

**Comment by gabrc52** [comment]
wontfix for now but the systemd unit now has auto-restart so a crash doesn't make it completely implode, presumably that's what Heroku does and it was fine(tm)
